// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Crossed Sports Arena - Transform Your Limits',
  description: 'Experience the ultimate fitness journey at Crossed Sports Arena. State-of-the-art equipment, expert trainers, and personalized workout plans.',
  keywords: 'gym, fitness, workout, training, sports arena, personal trainer, fitness center',
  authors: [{ name: 'Crossed Sports Arena' }],
  creator: 'Crossed Sports Arena',
  publisher: 'Crossed Sports Arena',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://crossedsportsarena.com'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'Crossed Sports Arena - Transform Your Limits',
    description: 'Experience the ultimate fitness journey at Crossed Sports Arena',
    url: 'https://crossedsportsarena.com',
    siteName: 'Crossed Sports Arena',
    images: [
      {
        url: '/img/gym-reception.jpg',
        width: 1200,
        height: 630,
        alt: 'Crossed Sports Arena Reception',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Crossed Sports Arena - Transform Your Limits',
    description: 'Experience the ultimate fitness journey at Crossed Sports Arena',
    images: ['/img/gym-reception.jpg'],
    creator: '@crossedsportsarena',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link 
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" 
          rel="stylesheet" 
        />
        <meta name="theme-color" content="#000000" />
        <meta name="color-scheme" content="dark" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className="font-sans antialiased bg-black text-white">
        <div className="min-h-screen flex flex-col">
          <main className="flex-grow">
            {children}
          </main>
        </div>
        
        {/* Preload critical images */}
        <div className="hidden">
          <link rel="preload" as="image" href="/img/gym-reception.jpg" />
          <link rel="preload" as="image" href="/img/gym-interior-2.jpg" />
          <link rel="preload" as="image" href="/img/gym-interior-3.jpg" />
        </div>
      </body>
    </html>
  )
}